### ISSUE TITLE
Can you make the navigation work without JavaScript?

### ISSUE THREAD

**Issue by aarongustafson** [MichalKatuscak/5TipsForFasterWeb#1]
Please do and then use the update link you’ll get shortly to let us know it’s been fixed.

**Comment by MichalKatuscak** [comment]
In commit https://github.com/MichalKatuscak/5TipsForFasterWeb/commit/5a26054780ec6e363bd82085649aca1912aae040 it was fixed.
I used update link.
Please, download new version :)
